name: Check Linting And Formatting

on:
  push:
  pull_request:

jobs:
  linting_and_formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - uses: actions/cache@v4
        name: Configure npm caching
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/workflows/prettier.yml') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - name: Install dependencies
        run: |-
          npm install
      - name: Lint And Format
        run: |-
          npm run checkFormatAndLint
