name: Auto Prod PR
on:
  push:
    branches:
      - dev
jobs:
  prodPr:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - name: Reset dev branch
        run: |
          git fetch origin dev:dev
          git reset --hard dev
      - name: Prod PR
        uses: peter-evans/create-pull-request@v6
        with:
          branch: dev-to-main-branch
